### ISSUE TITLE
setuptools-scm isn't being packed into the wheelhouse

### ISSUE THREAD

**Issue by canonical-cgregan** [juju-solutions/layer-apache-hadoop-namenode#7]
Install hook fails on hadoop deployment, unable to complete bundle deploy.

Steps:
1) Pull down YAML file from http://bazaar.launchpad.net/~bigdata-dev/charms/bundles/apache-core-batch-processing/trunk/view/head:/bundle-dev.yaml
2) juju-quickstart bundle-dev.yaml from inside Openstack instance with environment up

Result:
https://pastebin.canonical.com/150158/

**Comment by kwmonroe** [comment]
This also affects resourcemanager and slave... And will probably affect any charm pulling in path.py (or any package utilizing setup_requires) since it does this:

https://github.com/jaraco/path.py/blob/3383d9a18c69961fb6e7d0b98e8a829cc53cd660/setup.py#L38

Which is bad because of this:

https://github.com/pypa/pip/issues/410

So we need to think about how we can determine pip deps at charm build time to handle the fact that stuff like path.py will need stuff like setuptools-scm.  And when I say "we need to think", I of course mean @johnsca.

**Comment by johnsca** [comment]
[This](https://pip.pypa.io/en/latest/reference/pip_install/#controlling-setup-requires) might help some during the install phase, but the wheelhouse build phase will still be broken;  we'd have to also manually include setuptools-scm and it would still break if other packages include anything else in `setup_requires`.

**Comment by johnsca** [comment]
With juju-solutions/layer-basic#51 and [juju-solutions/jujubigdata#eaa749d](https://github.com/juju-solutions/jujubigdata/commit/eaa749dea565e21c043e554740e053246728faba), this should be resolved.
